### ISSUE TITLE
struct.error: ushort format requires 0 <= number <= 0xffff

### ISSUE THREAD

**Issue by RiajulKashem** [adrobinoga/pyzatt#14]
* PyZatt version: 2.0.0
* Python version: 3.8
* Operating System: Windows 10

### Enroll Fingerprint
I Tried to enroll fingerprint according to test_other.py but i got this error :( 

```
Traceback (most recent call last):
  File "D:/Projects/GitHub/Tman/tman_tests/zkteco_test.py", line 42, in <module>
    outfile.write(z.download_fp(user1_id, user1_fp_idx))
  File "D:\Projects\GitHub\Tman\venv\lib\site-packages\pyzatt-2.0.0-py3.8.egg\pyzatt\zkmodules\data_user.py", line 291, in download_fp
    req_fp.extend(struct.pack('<H', self.id_to_sn(user_id)))
struct.error: ushort format requires 0 <= number <= 0xffff

```

**Comment by adrobinoga** [comment]
what device are you using?

**Comment by RiajulKashem** [comment]
> what device are you using?

ZKTeco K40 Device
